fdfs:
  max_file_size: 1024MB
  max_request_size: 1024MB
  so-timeout: 1501
  connect-timeout: 601
  tracker-list:
    - 192.168.183.38:22122
  pool: # apache.pool2
    max-total: 153
    max-wait-millis: 102
server:
  port: 8081
spring:
  aop:
    auto: true
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    lettuce:
      shutdown-timeout: 100ms
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
        max-active: 8
logging:
  config: classpath:logback.groovy
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs