fdfs:
  max_file_size: 1024MB
  max_request_size: 1024MB
  so-timeout: 1501
  connect-timeout: 601
  tracker-list:
    - 192.168.183.38:22122
  pool: # apache.pool2
    max-total: 153
    max-wait-millis: 102
spring:
  aop:
    auto: true
server:
  port: 8081